"use client";
import { Check, ChevronLeft } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { formatIcelandicDate, formatIcelandicTime } from "@/lib/datetime/iceland";
import { formatIsk, offerConditionLabel, type SellerOfferData } from "@/lib/offers/model";
import { recordSellerIntent } from "../actions";

type Intent = "accept" | "reject" | "counter_offer";
export function SellerOfferView({ offer, propertySlug }: { offer: SellerOfferData; propertySlug: string }) {
  const [intent,setIntent]=useState<Intent|null>(offer.latestIntent); const [pending,setPending]=useState(false); const [error,setError]=useState<string|null>(null); const difference=offer.amountIsk-offer.askingPriceIsk;
  async function select(next:Intent){setPending(true);setError(null);try{await recordSellerIntent(offer.id,propertySlug,next);setIntent(next);}catch(caught){setError(caught instanceof Error?caught.message:"Ekki tókst að senda valið.");}finally{setPending(false);}}
  return <div className="mx-auto max-w-[920px] px-4 pb-8 pt-8 sm:px-6 lg:px-8"><Link href={`/seller/${propertySlug}`} className="mo-button mo-button-text min-h-11 gap-1.5 text-[12px]"><ChevronLeft size={14}/>{offer.property}</Link><header className="mt-4 border-b border-white/[0.07] pb-8"><p className="text-[11px] uppercase tracking-[0.13em] text-[#819181]">Tilboð</p><h1 className="mt-3 text-[31px] font-semibold tracking-[-0.04em]">{formatIsk(offer.amountIsk)}</h1><p className="mt-3 text-[13px] text-[#7a827c]">{offer.property} · {offer.location}</p></header><dl className="grid grid-cols-2 gap-7 border-b border-white/[0.07] py-8 sm:grid-cols-4">{[["Mismunur",`${difference<0?"−":"+"}${formatIsk(Math.abs(difference))}`],["Gildir til",`${formatIcelandicDate(offer.validUntil)} · ${formatIcelandicTime(offer.validUntil)}`],["Afhending",formatIcelandicDate(`${offer.requestedHandoverDate}T12:00:00Z`)],["Skilyrði",offer.conditions.map(c=>offerConditionLabel(c.type)).join(", ")||"Engin"]].map(([label,value])=><div key={label}><dt className="text-[12px] text-[#69716b]">{label}</dt><dd className="mt-2 text-[14px] text-[#c8c9c2]">{value}</dd></div>)}</dl><section className="py-9"><p className="text-[11px] text-[#69716b]">Fasteignasali</p><h2 className="mt-2 text-[15px]">{offer.agent}</h2><p className="mt-7 border-l-2 border-[#6f846f] pl-5 text-[15px] leading-7 text-[#bfc2bb]">Ræddu við fasteignasalann áður en ákvörðun er staðfest. Val hér er aðeins viljayfirlýsing og ekki lögbindandi samþykki.</p></section>{intent?<section className="border-y border-[#6f846f]/25 py-7 text-[#a9b8a7]"><Check size={15} className="mr-2 inline"/>Val þitt hefur verið sent til {offer.agent}.</section>:<section className="border-t border-white/[0.07] pt-8"><h2 className="text-[17px] font-semibold">Hvernig viltu halda áfram?</h2><div className="mt-5 flex flex-wrap gap-3"><button disabled={pending} onClick={()=>void select("accept")} className="mo-button mo-button-primary min-h-12 px-5 text-base font-semibold">Ég vil samþykkja</button><button disabled={pending} onClick={()=>void select("counter_offer")} className="mo-button mo-button-secondary min-h-12 px-5 text-base">Ég vil ræða móttilboð</button><button disabled={pending} onClick={()=>void select("reject")} className="mo-button mo-button-danger min-h-12 px-4 text-base">Ég vil hafna</button></div>{error&&<p className="mt-3 text-[#c98279]">{error}</p>}</section>}</div>;
}
