import { FileText } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import type { ReactNode } from "react";
import { formatIcelandicDate } from "@/lib/datetime/iceland";
import { customerOfferStatusLabel, formatIsk } from "@/lib/offers/model";
import type { CustomerPropertySummary } from "@/lib/portal/customer";
import type { CustomerDocument, CustomerTask } from "@/lib/work-items/model";
import { CustomerWorkItems } from "./CustomerWorkItems";
import { CustomerJourney } from "./CustomerJourney";

export function CustomerPropertyOverview({ audience, slug, summary, tasks, documents, offers, listingReview }: { audience: "seller" | "buyer"; slug: string; summary: CustomerPropertySummary; tasks: CustomerTask[]; documents: CustomerDocument[]; offers: Array<{ id: string; status: string; amountIsk: number; validUntil: string }>; listingReview?: ReactNode }) {
  const facts = [["Ásett verð", formatIsk(summary.askingPriceIsk)], ["Stærð", summary.property.sizeSqm ? `${summary.property.sizeSqm} m²` : "—"], ["Svefnherbergi", summary.property.bedroomCount ?? "—"], ["Byggingarár", summary.property.yearBuilt ?? "—"]];
  const progressStages = audience === "seller"
    ? [{ value: "preparation", label: "Undirbúningur" }, { value: "listed", label: "Á sölu" }, { value: "viewings", label: "Skoðanir" }, { value: "offers", label: "Tilboð" }, { value: "contract", label: "Samningur" }, { value: "closing", label: "Frágangur" }, { value: "handover", label: "Afhending" }]
    : [{ value: "viewings", label: "Skoðun" }, { value: "offers", label: "Tilboð" }, { value: "contract", label: "Samningur" }, { value: "handover", label: "Afhending" }];
  return <div className="mx-auto max-w-[1180px] px-4 pb-10 pt-8 sm:px-6 sm:pt-12 lg:px-8">
    <header className="kelvo-card grid overflow-hidden md:grid-cols-[minmax(280px,42%)_1fr] md:items-stretch">
      <div className="seller-property-image relative min-h-[230px] overflow-hidden md:min-h-[330px]">{summary.coverImageUrl ? <Image unoptimized fill sizes="(max-width: 768px) 100vw, 500px" src={summary.coverImageUrl} alt={`Mynd af ${summary.property.address}`} className="z-10 object-cover" /> : <span className="seller-building"><span className="seller-windows" /></span>}</div>
      <div className="flex flex-col justify-center p-6 sm:p-8"><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-[#667d5d]">{audience === "seller" ? "Eignin þín" : "Eign sem þú hefur áhuga á"}</p><h1 className="mt-3 text-[30px] font-bold tracking-[-0.04em] text-[var(--text-primary)] sm:text-[36px]">{summary.property.address}</h1><p className="mt-2 text-[14px] text-[var(--text-secondary)]">{summary.property.postalCode} {summary.property.municipality}</p><div className="mt-7 rounded-[14px] border border-black/[0.05] bg-[var(--surface-accent)] p-4"><p className="text-[10px] uppercase tracking-[0.09em] text-[#677866]">Fasteignasali</p><p className="mt-2 text-[13px] font-semibold text-[#334033]">{summary.agent.name}</p>{summary.agent.title && <p className="mt-1 text-[11px] text-[#697568]">{summary.agent.title}</p>}</div></div>
    </header>
    {listingReview}
    <section className="kelvo-card mt-6 p-5 sm:p-7"><h2 className="text-[19px] font-semibold text-[var(--text-primary)]">{audience === "seller" ? "Söluferli" : "Ferlið þitt"}</h2><CustomerJourney stages={progressStages} currentStage={summary.stage} />{summary.stage === "contract" && <p className="mt-5 rounded-[12px] bg-[var(--surface-accent)] px-4 py-3 text-[13px] text-[#5f705c]">Kaupsamningur í undirbúningi. Fasteignasalinn mun hafa samband vegna næstu skrefa.</p>}<dl className="mt-6 grid grid-cols-2 gap-px overflow-hidden rounded-[14px] border border-black/[0.06] bg-black/[0.06] sm:grid-cols-4">{facts.map(([label,value]) => <div key={label} className="bg-white p-4 sm:p-5"><dd className="text-[18px] font-bold text-[var(--text-primary)]">{value}</dd><dt className="mt-2 text-[11px] text-[var(--text-secondary)]">{label}</dt></div>)}</dl></section>
    <div className="mt-6 grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><section className="kelvo-card p-5 sm:p-6"><h2 className="text-[19px] font-semibold text-[var(--text-primary)]">{audience === "seller" ? "Tilboð" : "Tilboðin þín"}</h2><div className="mt-4 border-t border-black/[0.06]">{offers.map((offer) => <Link key={offer.id} href={`/${audience}/${slug}/offers/${offer.id}`} className="mo-hover-row flex min-h-[72px] items-center justify-between rounded-[10px] border-b border-black/[0.06] px-2 py-3"><div><p className="text-[15px] font-semibold text-[var(--text-primary)]">{formatIsk(offer.amountIsk)}</p><p className={offer.status === "accepted" ? "mt-1 text-[11px] text-[#58704f]" : "mt-1 text-[11px] text-[var(--text-secondary)]"}>{customerOfferStatusLabel(offer.status)} · gildir til {formatIcelandicDate(offer.validUntil)}</p></div><span className="text-[11px] font-semibold text-[#526545]">Skoða</span></Link>)}{!offers.length && <p className="border-b border-black/[0.06] py-5 text-[13px] text-[var(--text-secondary)]">Engin virk tilboð.</p>}</div>{audience === "buyer" && !offers.some((offer) => offer.status === "accepted") && <Link href={`/buyer/${slug}/offer`} className="mo-button mo-button-primary mt-6 min-h-11 px-5 text-base font-semibold">Gera tilboð</Link>}</section><aside className="kelvo-card p-5 sm:p-6"><h2 className="mb-5 text-[19px] font-semibold text-[var(--text-primary)]">Skjöl og verkefni</h2><CustomerWorkItems tasks={tasks} documents={documents} /></aside></div>
    <section className="kelvo-card mt-6 p-5 sm:p-6"><h2 className="text-[19px] font-semibold text-[var(--text-primary)]">Tengiliður</h2><p className="mt-4 text-[14px] font-semibold text-[#343934]">{summary.agent.name}</p>{summary.agent.title && <p className="mt-2 text-[13px] text-[var(--text-secondary)]">{summary.agent.title}</p>}{summary.agent.phone && <p className="mt-2 text-[13px] text-[var(--text-secondary)]">{summary.agent.phone}</p>}{summary.agent.email && <p className="mt-2 text-[13px] text-[var(--text-secondary)]">{summary.agent.email}</p>}<div className="mt-7 flex items-center gap-3 text-[#60765d]"><FileText size={15} /><span className="text-[12px]">Öll gögn eru afmörkuð við þessa eign.</span></div></section>
  </div>;
}
