import { FileText } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import type { ReactNode } from "react";
import { formatIcelandicDate } from "@/lib/datetime/iceland";
import { customerOfferStatusLabel, formatIsk } from "@/lib/offers/model";
import type { CustomerPropertySummary } from "@/lib/portal/customer";
import type { CustomerDocument, CustomerTask } from "@/lib/work-items/model";
import { CustomerWorkItems } from "./CustomerWorkItems";

export function CustomerPropertyOverview({ audience, slug, summary, tasks, documents, offers, listingReview }: { audience: "seller" | "buyer"; slug: string; summary: CustomerPropertySummary; tasks: CustomerTask[]; documents: CustomerDocument[]; offers: Array<{ id: string; status: string; amountIsk: number; validUntil: string }>; listingReview?: ReactNode }) {
  const facts = [["Ásett verð", formatIsk(summary.askingPriceIsk)], ["Stærð", summary.property.sizeSqm ? `${summary.property.sizeSqm} m²` : "—"], ["Svefnherbergi", summary.property.bedroomCount ?? "—"], ["Byggingarár", summary.property.yearBuilt ?? "—"]];
  const stageLabel = ({ valuation: "Verðmat", preparation: "Undirbúningur", listed: "Á sölu", viewings: "Skoðanir", offers: "Tilboð", contract: "Undirbúningur samnings", closing: "Frágangur", handover: "Afhending", completed: "Lokið", cancelled: "Hætt við" } as Record<string, string>)[summary.stage ?? ""] ?? summary.stage;
  return <div className="mx-auto max-w-[1180px] px-4 pb-10 pt-10 sm:px-6 sm:pt-14 lg:px-8">
    <header className="grid gap-7 border-b border-white/[0.07] pb-9 md:grid-cols-[260px_1fr] md:items-center">
      <div className="seller-property-image relative min-h-[180px] overflow-hidden rounded-[11px] border border-white/[0.08]">{summary.coverImageUrl ? <Image unoptimized fill sizes="260px" src={summary.coverImageUrl} alt="" className="z-10 object-cover" /> : <span className="seller-building"><span className="seller-windows" /></span>}</div>
      <div><p className="text-[11px] font-medium uppercase tracking-[0.14em] text-[#819181]">{audience === "seller" ? "Eignin þín" : "Eign sem þú hefur áhuga á"}</p><h1 className="mt-3 text-[30px] font-semibold tracking-[-0.04em]">{summary.property.address}</h1><p className="mt-2 text-[14px] text-[#858d87]">{summary.property.postalCode} {summary.property.municipality}</p><p className="mt-6 text-[12px] text-[#899289]">Fasteignasali: <span className="text-[#c7c9c2]">{summary.agent.name}</span>{summary.agent.title ? ` · ${summary.agent.title}` : ""}</p></div>
    </header>
    {listingReview}
    <section className="mt-10"><p className="text-[11px] uppercase tracking-[0.12em] text-[#819181]">Staða</p><h2 className="mt-2 text-[20px] font-semibold">{stageLabel ?? (audience === "seller" ? "Söluferli" : "Áhugi")}</h2>{summary.stage === "contract" && <p className="mt-3 text-[13px] text-[#8f9d8e]">Kaupsamningur í undirbúningi. Fasteignasalinn mun hafa samband vegna næstu skrefa.</p>}<dl className="mt-6 grid grid-cols-2 border-y border-white/[0.07] py-6 sm:grid-cols-4 sm:divide-x sm:divide-white/[0.07]">{facts.map(([label,value]) => <div key={label} className="sm:px-6 sm:first:pl-0"><dd className="text-[18px] font-semibold text-[#e8e6df]">{value}</dd><dt className="mt-2 text-[12px] text-[#777f79]">{label}</dt></div>)}</dl></section>
    <div className="mt-12 grid gap-12 lg:grid-cols-[1.15fr_.85fr] lg:gap-16"><section><h2 className="text-[19px] font-semibold">{audience === "seller" ? "Tilboð" : "Tilboðin þín"}</h2><div className="mt-5 border-t border-white/[0.07]">{offers.map((offer) => <Link key={offer.id} href={`/${audience}/${slug}/offers/${offer.id}`} className="mo-hover-row flex min-h-16 items-center justify-between border-b border-white/[0.07] py-3"><div><p className="text-[14px] font-medium text-[#e2e0d9]">{formatIsk(offer.amountIsk)}</p><p className={offer.status === "accepted" ? "mt-1 text-[11px] text-[#9caf9a]" : "mt-1 text-[11px] text-[#747c76]"}>{customerOfferStatusLabel(offer.status)} · gildir til {formatIcelandicDate(offer.validUntil)}</p></div><span className="text-[11px] text-[#91a18f]">Skoða</span></Link>)}{!offers.length && <p className="border-b border-white/[0.07] py-5 text-[13px] text-[#747c76]">Engin virk tilboð.</p>}</div>{audience === "buyer" && !offers.some((offer) => offer.status === "accepted") && <Link href={`/buyer/${slug}/offer`} className="mo-button mo-button-primary mt-6 min-h-11 px-5 text-base font-semibold">Gera tilboð</Link>}</section><aside className="border-t border-white/[0.07] pt-9 lg:border-l lg:border-t-0 lg:pl-10 lg:pt-0"><h2 className="mb-5 text-[19px] font-semibold">Skjöl og verkefni</h2><CustomerWorkItems tasks={tasks} documents={documents} /></aside></div>
    <section className="mt-12 border-t border-white/[0.07] pt-9"><h2 className="text-[19px] font-semibold">Tengiliður</h2><p className="mt-4 text-[14px] text-[#c8c9c2]">{summary.agent.name}</p>{summary.agent.title && <p className="mt-2 text-[13px] text-[#7f8781]">{summary.agent.title}</p>}{summary.agent.phone && <p className="mt-2 text-[13px] text-[#7f8781]">{summary.agent.phone}</p>}{summary.agent.email && <p className="mt-2 text-[13px] text-[#7f8781]">{summary.agent.email}</p>}<div className="mt-7 flex items-center gap-3 text-[#788679]"><FileText size={15} /><span className="text-[12px]">Öll gögn eru afmörkuð við þessa eign.</span></div></section>
  </div>;
}
