"use client";

import { ChevronRight, FileText } from "lucide-react";
import Link from "next/link";
import Image from "next/image";
import { useState, type ReactNode } from "react";
import { TransactionLifecycle } from "@/app/components/TransactionLifecycle";
import { formatIcelandicDate, formatIcelandicTime } from "@/lib/datetime/iceland";
import { formatIsk, offerConditionLabel } from "@/lib/offers/model";
import type { PropertyWorkspaceData } from "@/lib/properties/workspace";
import { ListingPreparation } from "./ListingPreparation";
import { PropertyImageManager } from "./PropertyImageManager";

const stageLabels: Record<string, string> = { valuation: "Verðmat", preparation: "Undirbúningur", listed: "Á sölu", viewings: "Skoðanir", offers: "Tilboð", contract: "Samningur", closing: "Frágangur", handover: "Afhending", completed: "Lokið", cancelled: "Hætt við" };
const tabs = ["Yfirlit", "Skráning", "Skoðanir", "Tilboð", "Verkefni", "Skjöl", "Virkni"] as const;
const contractTaskTitles = ["Staðfesta fjármögnun", "Yfirfara skilyrði tilboðs", "Staðfesta afhendingardag", "Safna nauðsynlegum skjölum", "Undirbúa kaupsamning", "Bóka undirritun"];
const taskStatusLabels: Record<string, string> = { not_started: "Ekki hafið", in_progress: "Í vinnslu", completed: "Lokið", cancelled: "Hætt við" };

function ListSection({ title, empty, count, children }: { title: string; empty: string; count: number; children: ReactNode }) { return <section className="kelvo-card mt-6 p-5 sm:p-6"><h2 className="text-[16px] font-semibold text-[var(--text-primary)]">{title}</h2><div className="mt-4 border-t border-black/[0.06]">{count ? children : <p className="py-10 text-[12px] text-[var(--text-secondary)]">{empty}</p>}</div></section>; }

export function PropertyWorkspace({ property, canEdit, canEditListing }: { property: PropertyWorkspaceData; canEdit: boolean; canEditListing: boolean }) {
  const [tab, setTab] = useState<(typeof tabs)[number]>("Yfirlit");
  const facts = [["Ásett verð", property.askingPriceIsk === null ? "Ekki skráð" : formatIsk(property.askingPriceIsk)], ["Stærð", property.sizeSqm === null ? "—" : `${property.sizeSqm} m²`], ["Herbergi", property.roomCount === null ? "—" : String(property.roomCount)], ["Svefnherbergi", property.bedroomCount === null ? "—" : String(property.bedroomCount)], ["Byggingarár", property.yearBuilt === null ? "—" : String(property.yearBuilt)], ["Fastanúmer", property.registryNumber ?? "—"]];

  const cover = property.images.find((image) => image.isCover) ?? property.images[0];
  const acceptedOffer = property.offers.find((offer) => offer.status === "accepted");
  const contractTasks = contractTaskTitles.flatMap((title) => {
    const task = property.tasks.find((item) => item.title === title);
    return task ? [task] : [];
  });
  const completedContractTasks = contractTasks.filter((task) => task.status === "completed").length;
  return <><header className="kelvo-card grid overflow-hidden md:grid-cols-[minmax(220px,34%)_1fr]"><div className="property-image property-image-city relative min-h-[180px] overflow-hidden md:min-h-[220px]">{cover?.url ? <Image unoptimized fill sizes="(max-width: 768px) 100vw, 420px" src={cover.url} alt={`Forsíðumynd af ${property.address}`} className="z-10 object-cover" /> : <span className="property-building" />}</div><div className="flex flex-col justify-center p-5 sm:p-7"><div className="flex flex-wrap items-center gap-3"><h1 className="text-[28px] font-bold tracking-[-0.04em] text-[var(--text-primary)] sm:text-[32px]">{property.address}</h1><span className="kelvo-status-progress rounded-full px-3 py-1.5 text-[9.5px] font-semibold">{stageLabels[property.stage] ?? property.stage}</span></div><p className="mt-2 text-[12px] text-[var(--text-secondary)]">{property.postalCode} {property.municipality}</p><dl className="mt-6 grid gap-4 border-t border-black/[0.06] pt-5 sm:grid-cols-3"><div><dt className="text-[9px] font-medium uppercase tracking-[0.08em] text-[var(--text-muted)]">Ásett verð</dt><dd className="mt-1.5 text-[13px] font-semibold text-[var(--text-primary)]">{property.askingPriceIsk === null ? "Ekki skráð" : formatIsk(property.askingPriceIsk)}</dd></div><div><dt className="text-[9px] font-medium uppercase tracking-[0.08em] text-[var(--text-muted)]">Seljandi</dt><dd className="mt-1.5 truncate text-[12px] text-[#3f463f]">{property.sellers.join(", ") || "Ekki skráður"}</dd></div><div><dt className="text-[9px] font-medium uppercase tracking-[0.08em] text-[var(--text-muted)]">Umsjón</dt><dd className="mt-1.5 truncate text-[12px] text-[#3f463f]">{property.agent}{property.agentTitle ? ` · ${property.agentTitle}` : ""}</dd></div></dl></div></header>
    <TransactionLifecycle currentStage={property.stage} />
    <nav className="mt-5 overflow-x-auto rounded-[14px] border border-black/[0.06] bg-white p-1.5" aria-label="Vinnusvæði eignar"><div className="flex min-w-max gap-1">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={`mo-tab h-10 rounded-[10px] px-4 text-[10.5px] font-semibold ${tab === item ? "bg-[var(--surface-accent)] text-[#34432f]" : "text-[var(--text-secondary)]"}`}>{item}</button>)}</div></nav>
    {tab === "Yfirlit" && <div className="py-6"><div className="grid gap-5 lg:grid-cols-[1.25fr_.75fr]"><section className="kelvo-card p-5 sm:p-6"><h2 className="text-[16px] font-semibold text-[var(--text-primary)]">Staða viðskipta</h2><dl className="mt-4 grid grid-cols-2 border-t border-black/[0.06] sm:grid-cols-3">{facts.map(([label,value]) => <div key={label} className="border-b border-black/[0.06] py-4"><dt className="text-[9.5px] text-[var(--text-muted)]">{label}</dt><dd className="mt-2 text-[12px] font-semibold text-[#343934]">{value}</dd></div>)}</dl></section><aside className="kelvo-card p-5 sm:p-6"><h2 className="text-[16px] font-semibold text-[var(--text-primary)]">Næstu atriði</h2><div className="mt-4 border-t border-black/[0.06]"><p className="border-b border-black/[0.06] py-4 text-[12px] text-[#4f5650]">{property.tasks.find((task) => !["completed","cancelled"].includes(task.status))?.title ?? "Engin opin verkefni"}</p><p className="border-b border-black/[0.06] py-4 text-[12px] text-[#4f5650]">{property.viewings.find((viewing) => viewing.status === "scheduled") ? "Næsta skoðun er skráð" : "Engin næsta skoðun skráð"}</p></div></aside></div>
      {property.stage === "contract" && acceptedOffer && <section className="kelvo-card mt-5 p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-[#667d5d]">Samningsferli</p><h2 className="mt-2 text-[18px] font-semibold text-[var(--text-primary)]">Undirbúningur kaupsamnings</h2><p className="mt-2 text-[11px] text-[var(--text-secondary)]">{completedContractTasks} af {contractTaskTitles.length} lokið</p></div><div className="flex items-center gap-3"><Link href="/tasks" className="mo-button mo-button-secondary min-h-11 px-4 text-[11px]">Opna verkefni</Link><Link href={`/properties/${property.slug}/offers/${acceptedOffer.id}`} className="mo-button mo-button-text min-h-11 text-[11px]">Skoða tilboð <ChevronRight size={14} /></Link></div></div><dl className="mt-5 grid gap-5 border-y border-black/[0.06] py-5 sm:grid-cols-4"><div><dt className="text-[10px] text-[var(--text-muted)]">Kaupandi</dt><dd className="mt-2 text-[12px] text-[#343934]">{acceptedOffer.buyerName}</dd></div><div><dt className="text-[10px] text-[var(--text-muted)]">Samþykkt upphæð</dt><dd className="mt-2 text-[12px] text-[#343934]">{formatIsk(acceptedOffer.amountIsk)}</dd></div><div><dt className="text-[10px] text-[var(--text-muted)]">Óskuð afhending</dt><dd className="mt-2 text-[12px] text-[#343934]">{formatIcelandicDate(`${acceptedOffer.requestedHandoverDate}T12:00:00Z`)}</dd></div><div><dt className="text-[10px] text-[var(--text-muted)]">Skilyrði</dt><dd className="mt-2 text-[12px] text-[#343934]">{acceptedOffer.conditions.map((condition) => offerConditionLabel(condition.type)).join(", ") || "Engin"}</dd></div></dl><div className="mt-7"><div className="h-1.5 overflow-hidden rounded-full bg-[#e8ece6]"><div className="h-full bg-[var(--mint-strong)] transition-[width] duration-150" style={{ width: `${(completedContractTasks / contractTaskTitles.length) * 100}%` }} /></div><div className="mt-4 border-t border-black/[0.06]">{contractTaskTitles.map((title) => { const task = contractTasks.find((item) => item.title === title); return <div key={title} className="flex min-h-12 items-center justify-between gap-4 border-b border-black/[0.06]"><div className="flex items-center gap-3"><span className={task?.status === "completed" ? "h-2 w-2 rounded-full bg-[#7d9676]" : task?.status === "in_progress" ? "h-2 w-2 rounded-full bg-[#b98a3f]" : "h-2 w-2 rounded-full bg-[#c9cec8]"} /><span className={task?.status === "completed" ? "text-[11px] text-[var(--text-secondary)]" : "text-[11px] text-[#434943]"}>{title}</span></div><span className="text-[10px] text-[var(--text-muted)]">{task ? taskStatusLabels[task.status] ?? task.status : "Bíður stofnunar"}</span></div>; })}</div><p className="mt-3 text-[10px] text-[var(--text-muted)]">Verkefnin eru innri undirbúningur. Kaupsamningur hefur ekki verið stofnaður eða undirritaður í Kelvo.</p></div></section>}
    </div>}
    {tab === "Skráning" && <ListingPreparation property={property} canEdit={canEditListing} />}
    {tab === "Skoðanir" && <ListSection title="Skoðanir" empty="Engar skoðanir hafa verið skráðar." count={property.viewings.length}>{property.viewings.map((viewing) => <Link key={viewing.id} href={`/properties/${property.slug}/viewings/${viewing.id}`} className="mo-hover-row flex min-h-16 items-center justify-between rounded-[10px] border-b border-black/[0.06] px-2 py-3"><div><p className="text-[12px] font-semibold text-[var(--text-primary)]">{viewing.type === "open_house" ? "Opið hús" : "Skoðun"}</p><p className="mt-1 text-[10.5px] text-[var(--text-secondary)]">{formatIcelandicDate(viewing.startsAt)} · {formatIcelandicTime(viewing.startsAt)}–{formatIcelandicTime(viewing.endsAt)}</p></div><ChevronRight size={15} className="text-[var(--text-muted)]" /></Link>)}</ListSection>}
    {tab === "Tilboð" && <ListSection title="Tilboð" empty="Engin tilboð hafa borist." count={property.offers.length}>{property.offers.map((offer) => <Link key={offer.id} href={`/properties/${property.slug}/offers/${offer.id}`} className="mo-hover-row flex min-h-16 items-center justify-between rounded-[10px] border-b border-black/[0.06] px-2 py-3"><div><p className="text-[13px] font-semibold text-[var(--text-primary)]">{formatIsk(offer.amountIsk)}</p><p className="mt-1 text-[10.5px] text-[var(--text-secondary)]">{offer.status} · gildir til {formatIcelandicDate(offer.validUntil)}</p></div><ChevronRight size={15} className="text-[var(--text-muted)]" /></Link>)}</ListSection>}
    {tab === "Verkefni" && <ListSection title="Verkefni" empty="Engin verkefni skráð." count={property.tasks.length}>{property.tasks.map((task) => <div key={task.id} className="flex min-h-16 items-center justify-between border-b border-black/[0.06] py-3"><div><p className="text-[12px] font-medium text-[var(--text-primary)]">{task.title}</p><p className="mt-1 text-[10.5px] text-[var(--text-secondary)]">{task.assignee ?? "Óúthlutað"}</p></div><span className="kelvo-status-neutral rounded-full px-2.5 py-1 text-[9px]">{task.status}</span></div>)}</ListSection>}
    {tab === "Skjöl" && <ListSection title="Skjöl" empty="Engin skjöl skráð." count={property.documents.length}>{property.documents.map((document) => <div key={document.id} className="flex min-h-16 items-center gap-3 border-b border-black/[0.06] py-3"><FileText size={14} className="text-[#60765d]" /><div className="flex-1"><p className="text-[12px] font-medium text-[var(--text-primary)]">{document.title}</p><p className="mt-1 text-[10.5px] text-[var(--text-secondary)]">{document.documentType}</p></div><span className="kelvo-status-neutral rounded-full px-2.5 py-1 text-[9px]">{document.visibility}</span></div>)}</ListSection>}
    {tab === "Virkni" && <ListSection title="Nýleg virkni" empty="Engin virkni skráð." count={property.activities.length}>{property.activities.map((activity) => <div key={activity.id} className="border-b border-black/[0.06] py-4"><p className="text-[12px] text-[#3f463f]">{activity.summary}</p><p className="mt-1 text-[10px] text-[var(--text-muted)]">{formatIcelandicDate(activity.createdAt)} · {formatIcelandicTime(activity.createdAt)}</p></div>)}</ListSection>}
    <PropertyImageManager slug={property.slug} images={property.images} canEdit={canEdit} />
  </>;
}
