"use client";

import { ChevronRight, FileText } from "lucide-react";
import Link from "next/link";
import { useState, type ReactNode } from "react";
import { formatIcelandicDate, formatIcelandicTime } from "@/lib/datetime/iceland";
import { formatIsk } from "@/lib/offers/model";
import type { PropertyWorkspaceData } from "@/lib/properties/workspace";

const stages = ["valuation", "preparation", "listed", "viewings", "offers", "contract", "closing", "handover"];
const stageLabels: Record<string, string> = { valuation: "Verðmat", preparation: "Undirbúningur", listed: "Á sölu", viewings: "Skoðanir", offers: "Tilboð", contract: "Samningur", closing: "Frágangur", handover: "Afhending", completed: "Lokið", cancelled: "Hætt við" };
const tabs = ["Yfirlit", "Skoðanir", "Tilboð", "Verkefni", "Skjöl", "Virkni"] as const;

function ListSection({ title, empty, count, children }: { title: string; empty: string; count: number; children: ReactNode }) { return <section className="py-8"><h2 className="text-[16px] font-semibold">{title}</h2><div className="mt-5 border-t border-white/[0.07]">{count ? children : <p className="py-10 text-[12px] text-[#737b75]">{empty}</p>}</div></section>; }

export function PropertyWorkspace({ property }: { property: PropertyWorkspaceData }) {
  const [tab, setTab] = useState<(typeof tabs)[number]>("Yfirlit");
  const currentStage = stages.indexOf(property.stage);
  const facts = [["Ásett verð", property.askingPriceIsk === null ? "Ekki skráð" : formatIsk(property.askingPriceIsk)], ["Stærð", property.sizeSqm === null ? "—" : `${property.sizeSqm} m²`], ["Herbergi", property.roomCount === null ? "—" : String(property.roomCount)], ["Svefnherbergi", property.bedroomCount === null ? "—" : String(property.bedroomCount)], ["Byggingarár", property.yearBuilt === null ? "—" : String(property.yearBuilt)], ["Fastanúmer", property.registryNumber ?? "—"]];

  return <><header className="grid gap-6 border-b border-white/[0.07] pb-7 md:grid-cols-[96px_1fr_auto] md:items-center"><div className="property-image property-image-city h-20 w-24 rounded-[10px] border border-white/[0.08]"><span className="property-building" /></div><div><div className="flex flex-wrap items-center gap-3"><h1 className="text-[26px] font-semibold tracking-[-0.035em]">{property.address}</h1><span className="rounded-full border border-[#6f846f]/30 bg-[#6f846f]/10 px-2.5 py-1 text-[9.5px] font-medium text-[#a9b8a7]">{stageLabels[property.stage] ?? property.stage}</span></div><p className="mt-2 text-[11px] text-[#7a827c]">{property.postalCode} {property.municipality}</p><p className="mt-4 text-[10.5px] text-[#8b938d]">Seljandi: {property.sellers.join(", ") || "Ekki skráður"} · Umsjón: {property.agent}</p></div><div className="text-left md:text-right"><p className="text-[10px] text-[#687069]">Viðskipti</p><p className="mt-1 font-mono text-[9px] text-[#8c948e]">{property.transactionId}</p></div></header>
    <section className="overflow-x-auto border-b border-white/[0.07] py-6" aria-label="Framvinda viðskipta"><ol className="flex min-w-[760px]">{stages.map((stage, index) => <li key={stage} className="relative flex-1 pt-5"><span className={`absolute left-0 right-0 top-1.5 h-px ${index <= currentStage ? "bg-[#6f846f]" : "bg-white/[0.08]"}`} /><span className={`absolute left-0 top-0 size-3 rounded-full border ${index === currentStage ? "border-[#9caf9a] bg-[#6f846f]" : index < currentStage ? "border-[#657565] bg-[#303a31]" : "border-[#3d443e] bg-[#111412]"}`} /><span className={index === currentStage ? "text-[10px] text-[#b8c6b5]" : "text-[10px] text-[#626a64]"}>{stageLabels[stage]}</span></li>)}</ol></section>
    <nav className="overflow-x-auto border-b border-white/[0.07]" aria-label="Vinnusvæði eignar"><div className="flex min-w-max gap-7">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={`mo-tab relative h-12 text-[10.5px] font-medium ${tab === item ? "text-[#b6c5b3]" : "text-[#68706a]"}`}>{item}{tab === item && <span className="absolute inset-x-0 bottom-0 h-px bg-[#9caf9a]" />}</button>)}</div></nav>
    {tab === "Yfirlit" && <div className="grid gap-10 py-8 lg:grid-cols-[1.25fr_.75fr] lg:gap-16"><section><h2 className="text-[16px] font-semibold">Staða viðskipta</h2><dl className="mt-5 grid grid-cols-2 border-t border-white/[0.07] sm:grid-cols-3">{facts.map(([label,value]) => <div key={label} className="border-b border-white/[0.07] py-4"><dt className="text-[9.5px] text-[#687069]">{label}</dt><dd className="mt-2 text-[12px] font-medium text-[#d7d7d0]">{value}</dd></div>)}</dl></section><aside><h2 className="text-[16px] font-semibold">Næstu atriði</h2><div className="mt-5 border-t border-white/[0.07]"><p className="border-b border-white/[0.07] py-4 text-[12px] text-[#aeb4ae]">{property.tasks.find((task) => !["completed","cancelled"].includes(task.status))?.title ?? "Engin opin verkefni"}</p><p className="border-b border-white/[0.07] py-4 text-[12px] text-[#aeb4ae]">{property.viewings.find((viewing) => viewing.status === "scheduled") ? "Næsta skoðun er skráð" : "Engin næsta skoðun skráð"}</p></div></aside></div>}
    {tab === "Skoðanir" && <ListSection title="Skoðanir" empty="Engar skoðanir hafa verið skráðar." count={property.viewings.length}>{property.viewings.map((viewing) => <Link key={viewing.id} href={`/properties/${property.slug}/viewings/${viewing.id}`} className="flex min-h-16 items-center justify-between border-b border-white/[0.07] py-3"><div><p className="text-[12px] font-medium text-[#deddd6]">{viewing.type === "open_house" ? "Opið hús" : "Skoðun"}</p><p className="mt-1 text-[10.5px] text-[#737b75]">{formatIcelandicDate(viewing.startsAt)} · {formatIcelandicTime(viewing.startsAt)}–{formatIcelandicTime(viewing.endsAt)}</p></div><ChevronRight size={15} className="text-[#59615b]" /></Link>)}</ListSection>}
    {tab === "Tilboð" && <ListSection title="Tilboð" empty="Engin tilboð hafa borist." count={property.offers.length}>{property.offers.map((offer) => <Link key={offer.id} href={`/properties/${property.slug}/offers/${offer.id}`} className="flex min-h-16 items-center justify-between border-b border-white/[0.07] py-3"><div><p className="text-[13px] font-medium text-[#deddd6]">{formatIsk(offer.amountIsk)}</p><p className="mt-1 text-[10.5px] text-[#737b75]">{offer.status} · gildir til {formatIcelandicDate(offer.validUntil)}</p></div><ChevronRight size={15} className="text-[#59615b]" /></Link>)}</ListSection>}
    {tab === "Verkefni" && <ListSection title="Verkefni" empty="Engin verkefni skráð." count={property.tasks.length}>{property.tasks.map((task) => <div key={task.id} className="flex min-h-16 items-center justify-between border-b border-white/[0.07] py-3"><div><p className="text-[12px] text-[#deddd6]">{task.title}</p><p className="mt-1 text-[10.5px] text-[#737b75]">{task.assignee ?? "Óúthlutað"}</p></div><span className="text-[10px] text-[#89978a]">{task.status}</span></div>)}</ListSection>}
    {tab === "Skjöl" && <ListSection title="Skjöl" empty="Engin skjöl skráð." count={property.documents.length}>{property.documents.map((document) => <div key={document.id} className="flex min-h-16 items-center gap-3 border-b border-white/[0.07] py-3"><FileText size={14} className="text-[#788679]" /><div className="flex-1"><p className="text-[12px] text-[#deddd6]">{document.title}</p><p className="mt-1 text-[10.5px] text-[#737b75]">{document.documentType}</p></div><span className="text-[10px] text-[#89978a]">{document.visibility}</span></div>)}</ListSection>}
    {tab === "Virkni" && <ListSection title="Nýleg virkni" empty="Engin virkni skráð." count={property.activities.length}>{property.activities.map((activity) => <div key={activity.id} className="border-b border-white/[0.07] py-4"><p className="text-[12px] text-[#c8c9c2]">{activity.summary}</p><p className="mt-1 text-[10px] text-[#69716b]">{formatIcelandicDate(activity.createdAt)} · {formatIcelandicTime(activity.createdAt)}</p></div>)}</ListSection>}
  </>;
}
