"use client";
import { Check, Plus, X } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import type { InternalTask, WorkOption } from "@/lib/work-items/model";
import { cancelTaskAction, completeTaskAction, createTaskAction, updateTaskAction } from "../actions";

const statusLabels={not_started:"Ekki hafið",in_progress:"Í vinnslu",completed:"Lokið",cancelled:"Hætt við"};
const visibilityLabels={internal:"Innri",seller:"Seljandi",buyer:"Kaupandi",seller_and_buyer:"Báðir"};
export function TaskManager({tasks,transactions,assignees}:{tasks:InternalTask[];transactions:WorkOption[];assignees:WorkOption[]}){const[show,setShow]=useState(false);const[pending,setPending]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);async function run(key:string,fn:()=>Promise<void>){setPending(key);setError(null);try{await fn();}catch(e){setError(e instanceof Error?e.message:"Aðgerð mistókst.");}finally{setPending(null);}}
return <><div className="flex justify-end"><button onClick={()=>setShow(!show)} className="inline-flex min-h-11 items-center gap-2 rounded-[8px] bg-[#6f846f] px-4 text-[12px] font-semibold text-[#111412]"><Plus size={14}/>Nýtt verkefni</button></div>{show&&<form action={(data)=>void run("create",()=>createTaskAction(data))} className="mt-5 grid gap-3 border-y border-white/[0.07] py-5 md:grid-cols-5"><input name="title" required placeholder="Heiti verkefnis" className="min-h-11 rounded-[8px] border border-white/[0.08] bg-[#181c19] px-3 text-base"/><select name="transactionId" required className="min-h-11 rounded-[8px] border border-white/[0.08] bg-[#181c19] px-3 text-base">{transactions.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><select name="assignedTo" className="min-h-11 rounded-[8px] border border-white/[0.08] bg-[#181c19] px-3 text-base"><option value="">Óúthlutað</option>{assignees.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><input name="dueAt" type="datetime-local" className="min-h-11 rounded-[8px] border border-white/[0.08] bg-[#181c19] px-3 text-base"/><div className="flex gap-2"><select name="visibility" className="min-h-11 min-w-0 flex-1 rounded-[8px] border border-white/[0.08] bg-[#181c19] px-2 text-base">{Object.entries(visibilityLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button disabled={pending==="create"} className="min-h-11 rounded-[8px] bg-[#6f846f] px-3 text-[12px] font-semibold text-[#111412]">Vista</button></div></form>}{error&&<p role="alert" className="mt-3 text-[12px] text-[#c98279]">{error}</p>}<div className="mt-6 border-t border-white/[0.07]">{tasks.map(task=><TaskRow key={task.id} task={task} assignees={assignees} pending={pending===task.id} run={(fn)=>run(task.id,fn)}/>) }{!tasks.length&&<p className="py-10 text-[13px] text-[#737b75]">Engin verkefni fundust.</p>}</div></>}
function TaskRow({task,assignees,pending,run}:{task:InternalTask;assignees:WorkOption[];pending:boolean;run:(fn:()=>Promise<void>)=>void}){const[status,setStatus]=useState(task.status);const[due,setDue]=useState(task.dueAt?.slice(0,16)??"");const[assigned,setAssigned]=useState(task.assigneeId??"");const overdue=task.dueAt&&new Date(task.dueAt)<new Date()&&!['completed','cancelled'].includes(task.status);return <article className="grid gap-3 border-b border-white/[0.07] py-4 lg:grid-cols-[1.4fr_.8fr_150px_175px_110px_auto] lg:items-center"><div><h2 className="text-[13px] font-medium text-[#e4e3dc]">{task.title}</h2><p className="mt-1 text-[10.5px] text-[#6f7771]"><Link href={`/properties/${task.propertySlug}`} className="hover:text-[#a9b8a7]">{task.property}</Link> · {visibilityLabels[task.visibility]}</p></div><select value={assigned} onChange={e=>setAssigned(e.target.value)} className="min-h-11 rounded-[8px] border border-white/[0.07] bg-[#171b18] px-2 text-base"><option value="">Óúthlutað</option>{assignees.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value as InternalTask["status"])} className="min-h-11 rounded-[8px] border border-white/[0.07] bg-[#171b18] px-2 text-base">{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input type="datetime-local" value={due} onChange={e=>setDue(e.target.value)} className={`min-h-11 rounded-[8px] border bg-[#171b18] px-2 text-base ${overdue?'border-[#c99a52]/50 text-[#c6a46f]':'border-white/[0.07]'}`}/><button disabled={pending} onClick={()=>run(()=>updateTaskAction(task.id,status,due,assigned,task.visibility))} className="min-h-11 rounded-[8px] border border-white/[0.09] px-3 text-[11px] text-[#aeb4ae]">Vista</button><div className="flex"><button aria-label="Ljúka" disabled={pending} onClick={()=>run(()=>completeTaskAction(task.id))} className="grid size-11 place-items-center text-[#93a590]"><Check size={15}/></button><button aria-label="Hætta við" disabled={pending} onClick={()=>run(()=>cancelTaskAction(task.id))} className="grid size-11 place-items-center text-[#9a716c]"><X size={15}/></button></div></article>}
