"use client";

import { useActionState, useState, useTransition } from "react";
import Image from "next/image";
import { Button } from "@/app/components/ui/Button";
import { Select } from "@/app/components/ui/Select";
import { inviteTeamMember, updateTeamMembership, type TeamState } from "./actions";

type Role="admin"|"agent"|"coordinator"|"viewer";
export type TeamMember={userId:string;name:string;email:string|null;title:string|null;role:Role;active:boolean;initials:string;photoUrl:string|null};
const options=[{value:"admin",label:"Stjórnandi"},{value:"agent",label:"Fasteignasali"},{value:"coordinator",label:"Umsjón"},{value:"viewer",label:"Lesaðgangur"}];
function MemberRow({member,canEdit}:{member:TeamMember;canEdit:boolean}){const[role,setRole]=useState<Role>(member.role);const[pending,start]=useTransition();const[error,setError]=useState<string|null>(null);function save(active=member.active){setError(null);start(async()=>{try{await updateTeamMembership(member.userId,role,active);}catch(caught){setError(caught instanceof Error?caught.message:"Aðgerð mistókst.");}});}return <article className="grid gap-3 border-b border-white/[0.07] py-4 md:grid-cols-[1fr_190px_120px_auto] md:items-center"><div className="flex items-center gap-3"><span className="relative grid size-9 overflow-hidden rounded-full bg-[#252c26] text-[10px] font-semibold text-[#b4c0b2]">{member.photoUrl?<Image unoptimized fill sizes="36px" src={member.photoUrl} alt="" className="object-cover"/>:<span className="grid size-full place-items-center">{member.initials}</span>}</span><div><p className="text-[13px] font-medium">{member.name}</p><p className="mt-1 text-[10px] text-[#737b75]">{member.email??"Netfang ekki skráð"}{member.title?` · ${member.title}`:""}</p>{error&&<p className="mt-1 text-[10px] text-[#c98279]">{error}</p>}</div></div><Select ariaLabel={`Hlutverk ${member.name}`} value={role} onChange={(value)=>setRole(value as Role)} options={options} disabled={!canEdit||pending}/><span className={member.active?"text-[11px] text-[#9caf9a]":"text-[11px] text-[#8b6863]"}>{member.active?"Virkur":"Óvirkur"}</span>{canEdit&&<div className="flex gap-2"><Button disabled={pending} onClick={()=>save()} className="min-h-11 px-3 text-[11px]">Vista</Button><Button variant={member.active?"danger":"secondary"} disabled={pending} onClick={()=>save(!member.active)} className="min-h-11 px-3 text-[11px]">{member.active?"Óvirkja":"Virkja"}</Button></div>}</article>}
function InviteMemberForm(){const[state,action,pending]=useActionState(inviteTeamMember,{error:null,success:null} satisfies TeamState);const[role,setRole]=useState<Role>("agent");return <form action={action} className="mt-10 grid gap-4 border-y border-white/[0.07] py-6 sm:grid-cols-[1fr_1fr_180px_auto]"><input name="displayName" required placeholder="Nafn" className="mo-control min-h-11 px-3 text-base outline-none"/><input name="email" type="email" required placeholder="Netfang" className="mo-control min-h-11 px-3 text-base outline-none"/><Select name="role" ariaLabel="Hlutverk" value={role} onChange={(value)=>setRole(value as Role)} options={options}/><Button type="submit" variant="primary" disabled={pending} className="min-h-11 px-4 text-[12px]">Bjóða í teymi</Button>{state.error&&<p className="sm:col-span-4 text-[12px] text-[#c98279]">{state.error}</p>}{state.success&&<p className="sm:col-span-4 text-[12px] text-[#9caf9a]">{state.success}</p>}</form>}
export function TeamManager({members,canEdit}:{members:TeamMember[];canEdit:boolean}){return <><section className="mt-7"><div className="border-t border-white/[0.07]">{members.map((member)=><MemberRow key={member.userId} member={member} canEdit={canEdit}/>)}</div></section>{canEdit&&<InviteMemberForm/>}</>}
