"use client";

import { useActionState, useState, useTransition } from "react";
import Image from "next/image";
import { Button } from "@/app/components/ui/Button";
import { Input } from "@/app/components/ui/Input";
import { Panel } from "@/app/components/ui/Panel";
import { Select } from "@/app/components/ui/Select";
import { StatusChip } from "@/app/components/ui/StatusChip";
import { inviteTeamMember, updateTeamMembership, type TeamState } from "./actions";

type Role="admin"|"agent"|"coordinator"|"viewer";
export type TeamMember={userId:string;name:string;email:string|null;title:string|null;role:Role;active:boolean;initials:string;photoUrl:string|null};
const options=[{value:"admin",label:"Stjórnandi"},{value:"agent",label:"Fasteignasali"},{value:"coordinator",label:"Umsjón"},{value:"viewer",label:"Lesaðgangur"}];
function MemberRow({member,canEdit}:{member:TeamMember;canEdit:boolean}){const[role,setRole]=useState<Role>(member.role);const[pending,start]=useTransition();const[error,setError]=useState<string|null>(null);function save(active=member.active){setError(null);start(async()=>{try{await updateTeamMembership(member.userId,role,active);}catch(caught){setError(caught instanceof Error?caught.message:"Aðgerð mistókst.");}});}return <article className="grid gap-3 border-b border-black/[0.06] px-2 py-4 last:border-b-0 md:grid-cols-[minmax(180px,1fr)_190px_100px_auto] md:items-center"><div className="flex items-center gap-3"><span className="relative grid size-10 overflow-hidden rounded-full bg-[var(--mint)] text-[10px] font-bold text-[#3f594c]">{member.photoUrl?<Image unoptimized fill sizes="40px" src={member.photoUrl} alt="" className="object-cover"/>:<span className="grid size-full place-items-center">{member.initials}</span>}</span><div className="min-w-0"><p className="truncate text-[13px] font-semibold text-[var(--text-primary)]">{member.name}</p><p className="mt-1 truncate text-[10px] text-[var(--text-secondary)]">{member.email??"Netfang ekki skráð"}{member.title?` · ${member.title}`:""}</p>{error&&<p className="mt-1 text-[10px] text-[#a24f48]">{error}</p>}</div></div><Select ariaLabel={`Hlutverk ${member.name}`} value={role} onChange={(value)=>setRole(value as Role)} options={options} disabled={!canEdit||pending} size="compact"/><StatusChip tone={member.active?"success":"neutral"}>{member.active?"Virkur":"Óvirkur"}</StatusChip>{canEdit&&<div className="flex gap-2 md:justify-end"><Button size="compact" disabled={pending} onClick={()=>save()}>Vista</Button><Button size="compact" variant={member.active?"danger":"secondary"} disabled={pending} onClick={()=>save(!member.active)}>{member.active?"Óvirkja":"Virkja"}</Button></div>}</article>}
function InviteMemberForm(){const[state,action,pending]=useActionState(inviteTeamMember,{error:null,success:null} satisfies TeamState);const[role,setRole]=useState<Role>("agent");return <Panel className="mt-6"><div className="mb-4"><h2 className="text-[16px] font-semibold text-[var(--text-primary)]">Bjóða í teymi</h2><p className="mt-1 text-[11px] text-[var(--text-secondary)]">Bættu við starfsfólki og veldu hlutverk.</p></div><form action={action} className="grid gap-4 sm:grid-cols-[1fr_1fr_180px_auto]"><Input name="displayName" required placeholder="Nafn"/><Input name="email" type="email" required placeholder="Netfang"/><Select name="role" ariaLabel="Hlutverk" value={role} onChange={(value)=>setRole(value as Role)} options={options}/><Button type="submit" variant="primary" disabled={pending}>Bjóða í teymi</Button>{state.error&&<p className="sm:col-span-4 text-[12px] text-[#a24f48]">{state.error}</p>}{state.success&&<p className="sm:col-span-4 text-[12px] text-[#58704f]">{state.success}</p>}</form></Panel>}
export function TeamManager({members,canEdit}:{members:TeamMember[];canEdit:boolean}){return <><Panel className="mt-6 overflow-hidden p-3 sm:p-4">{members.map((member)=><MemberRow key={member.userId} member={member} canEdit={canEdit}/>)}</Panel>{canEdit&&<InviteMemberForm/>}</>}
