import { Check, ChevronLeft } from "lucide-react";
import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { CustomerShell } from "@/app/components/CustomerShell";
import { PortalAccessDenied } from "@/app/components/PortalAccessDenied";
import { formatIcelandicDate, formatIcelandicTime } from "@/lib/datetime/iceland";
import { getBuyerOffer } from "@/lib/offers/detail";
import { formatIsk, offerConditionLabel } from "@/lib/offers/model";
import { customerInitials, getBuyerPropertySummary, getCustomerDestinationBySlug, getCustomerTransactionOffers } from "@/lib/portal/customer";
import { createClient } from "@/lib/supabase/server";

export default async function BuyerOfferPage({params}:{params:Promise<{propertySlug:string;offerId:string}>}){const{propertySlug,offerId}=await params;const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect(`/customer/login?next=/buyer/${propertySlug}/offers/${offerId}`);const destination=await getCustomerDestinationBySlug(propertySlug,"buyer",supabase);if(!destination.data)return <PortalAccessDenied/>;const[summary,offer,availableOffers]=await Promise.all([getBuyerPropertySummary(destination.data.transactionId),getBuyerOffer(offerId),getCustomerTransactionOffers(destination.data.transactionId,supabase)]);if(summary.denied||offer.denied)return <PortalAccessDenied/>;if(!summary.data||!offer.data||availableOffers.error||!availableOffers.data.some(item=>item.id===offerId))notFound();return <CustomerShell customerName={summary.data.customer.name} customerInitials={customerInitials(summary.data.customer.name)} customerRole="Kaupandi" homeHref={`/buyer/${propertySlug}`} portalLabel="Kaupendagátt"><div className="mx-auto max-w-[920px] px-4 py-10 sm:px-6"><Link href={`/buyer/${propertySlug}`} className="inline-flex min-h-11 items-center gap-1 text-[12px] text-[#78827a]"><ChevronLeft size={14}/>{summary.data.property.address}</Link><header className="mt-4 border-b border-white/[0.07] pb-8"><p className="text-[11px] uppercase tracking-[0.13em] text-[#819181]">Tilboð þitt</p><h1 className="mt-3 text-[31px] font-semibold">{formatIsk(offer.data.amountIsk)}</h1><p className="mt-3 text-[13px] text-[#9aaa98]">{offer.data.status}</p></header><dl className="grid gap-6 border-b border-white/[0.07] py-8 sm:grid-cols-3"><div><dt className="text-[11px] text-[#69716b]">Gildir til</dt><dd className="mt-2 text-[14px]">{formatIcelandicDate(offer.data.validUntil)} · {formatIcelandicTime(offer.data.validUntil)}</dd></div><div><dt className="text-[11px] text-[#69716b]">Afhending</dt><dd className="mt-2 text-[14px]">{formatIcelandicDate(`${offer.data.requestedHandoverDate}T12:00:00Z`)}</dd></div><div><dt className="text-[11px] text-[#69716b]">Skilyrði</dt><dd className="mt-2 text-[14px]">{offer.data.conditions.map(c=>offerConditionLabel(c.type)).join(", ")||"Engin"}</dd></div></dl><section className="mt-8 border-y border-[#6f846f]/25 py-6 text-[13px] text-[#a9b8a7]"><Check size={14} className="mr-2 inline"/>Tilboðið er í formlegu vinnuflæði fasteignasala.</section></div></CustomerShell>}
