"use server";
import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";

function refresh(){revalidatePath("/documents");revalidatePath("/properties","layout");revalidatePath("/seller","layout");revalidatePath("/buyer","layout");}
export async function uploadDocumentAction(formData:FormData){const file=formData.get("file");if(!(file instanceof File)||file.size===0)throw new Error("Veldu skrá.");const supabase=await createClient();const {data,error}=await supabase.rpc("create_document_record",{p_transaction_id:String(formData.get("transactionId")),p_title:String(formData.get("title")),p_document_type:String(formData.get("documentType")),p_visibility:String(formData.get("visibility")),p_file_name:file.name,p_mime_type:file.type||null,p_file_size_bytes:file.size,p_description:null});if(error)throw new Error(error.message);const document=Array.isArray(data)?data[0]:data;const {error:uploadError}=await supabase.storage.from("transaction-documents").upload(document.storage_path,file,{contentType:file.type||"application/octet-stream",upsert:false});if(uploadError){await supabase.rpc("delete_document_record",{p_document_id:document.id});throw new Error(uploadError.message);}refresh();}
export async function updateDocumentVisibilityAction(id:string,visibility:string){const supabase=await createClient();const{error}=await supabase.rpc("update_document_visibility",{p_document_id:id,p_visibility:visibility});if(error)throw new Error(error.message);refresh();}
export async function getDocumentDownloadUrl(id:string){const supabase=await createClient();const{data,error}=await supabase.rpc("authorize_document_download",{p_document_id:id});if(error)return{url:null,error:"Þú hefur ekki aðgang að skjalinu."};const row=data as{storage_path:string};const parts=row.storage_path.split("/");const fileName=parts.pop();const folder=parts.join("/");const{data:objects,error:listError}=await supabase.storage.from("transaction-documents").list(folder,{search:fileName,limit:10});if(listError)return{url:null,error:"Ekki tókst að staðfesta skrána í geymslu."};if(!objects?.some((object)=>object.name===fileName))return{url:null,error:"Aðeins lýsigögn eru til fyrir þetta skjal; skrá hefur ekki verið hlaðið upp."};const{data:signed,error:signedError}=await supabase.storage.from("transaction-documents").createSignedUrl(row.storage_path,60);return{url:signed?.signedUrl??null,error:signedError?"Ekki tókst að útbúa tímabundinn niðurhalshlekk.":null};}
export async function deleteDocumentAction(id:string){const supabase=await createClient();const{data,error}=await supabase.rpc("authorize_document_download",{p_document_id:id});if(error)throw new Error(error.message);const row=data as{storage_path:string};const{error:removeError}=await supabase.storage.from("transaction-documents").remove([row.storage_path]);if(removeError&&!/not found/i.test(removeError.message))throw new Error(removeError.message);const{error:deleteError}=await supabase.rpc("delete_document_record",{p_document_id:id});if(deleteError)throw new Error(deleteError.message);refresh();}
