"use client";
import { Download, Plus, Trash2 } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import type { DocumentVisibility, InternalDocument, WorkOption } from "@/lib/work-items/model";
import { deleteDocumentAction, getDocumentDownloadUrl, updateDocumentVisibilityAction, uploadDocumentAction } from "../actions";
const labels={internal:"Innri",seller:"Seljandi",buyer:"Kaupandi",shared:"Sameiginlegt"};
export function DocumentManager({documents,transactions}:{documents:InternalDocument[];transactions:WorkOption[]}){const[show,setShow]=useState(false);const[pending,setPending]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);async function run(key:string,fn:()=>Promise<void>){setPending(key);setError(null);try{await fn();}catch(e){setError(e instanceof Error?e.message:"Aðgerð mistókst.");}finally{setPending(null);}}async function download(id:string){setPending(id);const result=await getDocumentDownloadUrl(id);setPending(null);if(result.url)window.open(result.url,"_blank","noopener,noreferrer");else setError(result.error??"Skrá fannst ekki í geymslu.");}
return <><div className="flex justify-end"><button onClick={()=>setShow(!show)} className="inline-flex min-h-11 items-center gap-2 rounded-[8px] bg-[#6f846f] px-4 text-[12px] font-semibold text-[#111412]"><Plus size={14}/>Hlaða upp skjali</button></div>{show&&<form action={(data)=>void run("upload",()=>uploadDocumentAction(data))} className="mt-5 grid gap-3 border-y border-white/[0.07] py-5 md:grid-cols-2 lg:grid-cols-5"><input name="title" required placeholder="Heiti skjals" className="min-h-11 rounded-[8px] border border-white/[0.08] bg-[#181c19] px-3 text-base"/><input name="documentType" required placeholder="Tegund" className="min-h-11 rounded-[8px] border border-white/[0.08] bg-[#181c19] px-3 text-base"/><select name="transactionId" className="min-h-11 rounded-[8px] border border-white/[0.08] bg-[#181c19] px-3 text-base">{transactions.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><select name="visibility" className="min-h-11 rounded-[8px] border border-white/[0.08] bg-[#181c19] px-3 text-base">{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><div className="flex gap-2"><input name="file" type="file" required className="min-h-11 min-w-0 flex-1 text-base text-[#929a94] file:mr-2 file:min-h-11 file:border-0 file:bg-[#202620] file:px-3 file:text-[#bdc6bb]"/><button disabled={pending==="upload"} className="min-h-11 rounded-[8px] bg-[#6f846f] px-3 text-[12px] font-semibold text-[#111412]">Vista</button></div></form>}{error&&<p role="alert" className="mt-3 text-[12px] text-[#c98279]">{error}</p>}<div className="mt-6 border-t border-white/[0.07]">{documents.map(doc=><DocumentRow key={doc.id} document={doc} pending={pending===doc.id} run={(fn)=>run(doc.id,fn)} download={()=>void download(doc.id)}/>) }{!documents.length&&<p className="py-10 text-[13px] text-[#737b75]">Engin skjöl fundust.</p>}</div></>}
function DocumentRow({document,pending,run,download}:{document:InternalDocument;pending:boolean;run:(fn:()=>Promise<void>)=>void;download:()=>void}){const[visibility,setVisibility]=useState<DocumentVisibility>(document.visibility);return <article className="grid gap-3 border-b border-white/[0.07] py-4 md:grid-cols-[1.5fr_.7fr_150px_130px_auto] md:items-center"><div><h2 className="text-[13px] font-medium text-[#e4e3dc]">{document.title}</h2><p className="mt-1 text-[10.5px] text-[#6f7771]"><Link href={`/properties/${document.propertySlug}`} className="hover:text-[#a9b8a7]">{document.property}</Link> · {document.documentType}</p></div><p className="text-[11px] text-[#8b938d]">{document.uploadedBy}</p><select value={visibility} onChange={e=>setVisibility(e.target.value as DocumentVisibility)} className="min-h-11 rounded-[8px] border border-white/[0.07] bg-[#171b18] px-2 text-base">{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button disabled={pending} onClick={()=>run(()=>updateDocumentVisibilityAction(document.id,visibility))} className="min-h-11 rounded-[8px] border border-white/[0.09] px-3 text-[11px] text-[#aeb4ae]">Vista aðgang</button><div className="flex"><button aria-label="Sækja" disabled={pending} onClick={download} className="grid size-11 place-items-center text-[#93a590]"><Download size={15}/></button><button aria-label="Eyða" disabled={pending} onClick={()=>run(()=>deleteDocumentAction(document.id))} className="grid size-11 place-items-center text-[#9a716c]"><Trash2 size={15}/></button></div></article>}
