"use client";

import Link from "next/link";
import { Plus } from "lucide-react";
import { useActionState,useMemo,useState } from "react";
import { Button } from "@/app/components/ui/Button";
import { EmptyState } from "@/app/components/ui/EmptyState";
import { Input, SearchInput } from "@/app/components/ui/Input";
import { Panel } from "@/app/components/ui/Panel";
import { createContact,type ContactState } from "./actions";
type Contact={id:string;name:string;email:string|null;phone:string|null;contexts:string[];properties:string[]};
export function ContactDirectory({contacts,canEdit}:{contacts:Contact[];canEdit:boolean}){const[query,setQuery]=useState("");const[show,setShow]=useState(false);const[state,action,pending]=useActionState(createContact,{error:null} satisfies ContactState);const filtered=useMemo(()=>{const q=query.trim().toLocaleLowerCase("is-IS");return q?contacts.filter((contact)=>`${contact.name} ${contact.email??""} ${contact.phone??""} ${contact.properties.join(" ")}`.toLocaleLowerCase("is-IS").includes(q)):contacts;},[contacts,query]);return <><div className="mt-6 flex flex-col gap-3 sm:flex-row sm:justify-between"><label className="block max-w-md flex-1"><span className="sr-only">Leita að tengilið</span><SearchInput value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Leita eftir nafni, netfangi eða eign..."/></label>{canEdit&&<Button variant="primary" onClick={()=>setShow(!show)}><Plus size={14} />Nýr tengiliður</Button>}</div>{show&&<Panel className="mt-5"><form action={action} className="grid gap-3 sm:grid-cols-[1fr_1fr_160px_auto]"><Input name="name" required placeholder="Nafn"/><Input name="email" type="email" placeholder="Netfang"/><Input name="phone" placeholder="Sími"/><Button type="submit" variant="primary" disabled={pending}>Stofna</Button>{state.error&&<p className="sm:col-span-4 text-[12px] text-[#a24f48]">{state.error}</p>}</form></Panel>}<Panel className="mt-5 overflow-hidden p-3 sm:p-4">{filtered.map((contact)=><Link key={contact.id} href={`/contacts/${contact.id}`} className="mo-hover-row grid gap-3 rounded-[12px] border-b border-black/[0.06] px-2 py-4 last:border-b-0 sm:grid-cols-[1.1fr_1fr_.8fr_1.2fr] sm:items-center"><div><p className="text-[13px] font-semibold text-[var(--text-primary)]">{contact.name}</p><p className="mt-1 text-[10px] text-[var(--text-secondary)]">{contact.contexts.join(" · ")||"Tengiliður"}</p></div><p className="text-[11px] text-[var(--text-secondary)]">{contact.email??"—"}</p><p className="text-[11px] text-[var(--text-secondary)]">{contact.phone??"—"}</p><p className="text-[10px] text-[#60705f]">{contact.properties.join(", ")||"Engin tengd eign"}</p></Link>)}{!filtered.length&&<EmptyState>Engir tengiliðir fundust.</EmptyState>}</Panel></>}
