"use client";

import Link from "next/link";
import { Search } from "lucide-react";
import { useActionState,useMemo,useState } from "react";
import { Button } from "@/app/components/ui/Button";
import { createContact,type ContactState } from "./actions";
type Contact={id:string;name:string;email:string|null;phone:string|null;contexts:string[];properties:string[]};
export function ContactDirectory({contacts,canEdit}:{contacts:Contact[];canEdit:boolean}){const[query,setQuery]=useState("");const[show,setShow]=useState(false);const[state,action,pending]=useActionState(createContact,{error:null} satisfies ContactState);const filtered=useMemo(()=>{const q=query.trim().toLocaleLowerCase("is-IS");return q?contacts.filter((contact)=>`${contact.name} ${contact.email??""} ${contact.phone??""} ${contact.properties.join(" ")}`.toLocaleLowerCase("is-IS").includes(q)):contacts;},[contacts,query]);return <><div className="mt-7 flex flex-col gap-3 sm:flex-row sm:justify-between"><label className="relative block max-w-md flex-1"><span className="sr-only">Leita að tengilið</span><Search size={15} className="absolute left-3 top-3.5 text-[#69716b]"/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Leita eftir nafni, netfangi eða eign..." className="mo-control min-h-11 w-full pl-9 pr-3 text-base outline-none"/></label>{canEdit&&<Button variant="primary" onClick={()=>setShow(!show)} className="min-h-11 px-4 text-[12px]">Nýr tengiliður</Button>}</div>{show&&<form action={action} className="mt-5 grid gap-3 border-y border-white/[0.07] py-5 sm:grid-cols-[1fr_1fr_160px_auto]"><input name="name" required placeholder="Nafn" className="mo-control min-h-11 px-3 text-base outline-none"/><input name="email" type="email" placeholder="Netfang" className="mo-control min-h-11 px-3 text-base outline-none"/><input name="phone" placeholder="Sími" className="mo-control min-h-11 px-3 text-base outline-none"/><Button type="submit" variant="primary" disabled={pending} className="min-h-11 px-4 text-[12px]">Stofna</Button>{state.error&&<p className="sm:col-span-4 text-[12px] text-[#c98279]">{state.error}</p>}</form>}<div className="mt-7 border-t border-white/[0.07]">{filtered.map((contact)=><Link key={contact.id} href={`/contacts/${contact.id}`} className="mo-hover-row grid gap-3 border-b border-white/[0.07] py-4 sm:grid-cols-[1.1fr_1fr_.8fr_1.2fr] sm:items-center"><div><p className="text-[13px] font-medium text-[#e3e2db]">{contact.name}</p><p className="mt-1 text-[10px] text-[#747c76]">{contact.contexts.join(" · ")||"Tengiliður"}</p></div><p className="text-[11px] text-[#929a94]">{contact.email??"—"}</p><p className="text-[11px] text-[#929a94]">{contact.phone??"—"}</p><p className="text-[10px] text-[#788279]">{contact.properties.join(", ")||"Engin tengd eign"}</p></Link>)}{!filtered.length&&<p className="border-b border-white/[0.07] py-10 text-[12px] text-[#737b75]">Engir tengiliðir fundust.</p>}</div></>}
